# preload = /home/YOURUSER/dotfiles/.config/hypr/Wallpapers/desktop.jpg
#
# wallpaper = eDP-1,/home/YOURUSER/dotfiles/.config/hypr/Wallpapers/desktop.jpg
# wallpaper = DP-2,/home/YOURUSER/dotfiles/.config/hypr/Wallpapers/desktop.jpg

wallpaper {
    monitor = DP-2
    path = /home/varun/dotfiles/.config/hypr/Wallpapers/desktop.jpg
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = /home/varun/dotfiles/.config/hypr/Wallpapers/desktop.jpg
    fit_mode = cover
}

splash = false
