source = ~/.config/hypr/modules/variables.conf

# Master toggle to disable all keybinds
bind = $mainMod, F11, submap, clean

# Submap for clean (disabled state)
submap = clean

# Keybind to return to the default submap (re-enable keybinds)
bind = $mainMod SHIFT, F11, submap, reset

# Fullscreen toggle (active in clean submap)
bind = $mainMod, I, fullscreen,

# Submap for reset (default keybinds enabled)
submap = reset

bind = $mainMod, RETURN, exec, $terminalBash
bind = $mainMod SHIFT, RETURN, exec, $terminalZsh
bind = $mainMod, D, exec, discord 
bind = $mainMod, F, exec, firefox
bind = $mainMod, B, exec, blender
bind = $mainMod, C, killactive,
bind = $mainMod, M, exit, # REPLACEABLE
bind = $mainMod, G, exec, $fileManager
bind = $mainMod, U, togglefloating, # REPLACEABLE
bind = $mainMod, A, exec, $menu
bind = $mainMod, I, fullscreen,
bind = $mainMod, O, layoutmsg, togglesplit
bind = $mainMod, V, exec, kitty --override font_size=7 --title info-btop bash -c "btop"
bind = , Print, exec, grim -g "$(slurp)" - | wl-copy
bind = $mainMod, T, exec, kitty bash -c "nvim ~/notes/todo.txt"
bind = $mainMod SHIFT, T, exec, kitty bash -c "nvim ~/notes/journal.txt"
bind = $mainMod, Y, exec, hyprctl keyword decoration:screen_shader "./misc/shader.glsl"
bind = $mainMod SHIFT, Y, exec, hyprctl keyword decoration:screen_shader ""

bind = $mainMod SHIFT, M, exec, shutdown now
bind = $mainMod SHIFT, N, exec, reboot

bind = $mainMod SHIFT, z, movecurrentworkspacetomonitor, l
bind = $mainMod SHIFT, x, movecurrentworkspacetomonitor, r

# Move focus
bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r

# Move windows
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, J, movewindow, d
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, L, movewindow, r

# Resize windows
bind = $mainMod CTRL, H, resizeactive, -50 0
bind = $mainMod CTRL, J, resizeactive, 0 50
bind = $mainMod CTRL, K, resizeactive, 0 -50
bind = $mainMod CTRL, L, resizeactive, 50 0

bind = $mainMod, Q, workspace, 1
bind = $mainMod, W, workspace, 2
bind = $mainMod, E, workspace, 3
bind = $mainMod, R, workspace, 4
# for "locking"
# bind = $mainMod SHIFT, L, workspace, 10

bind = $mainMod SHIFT, Q, movetoworkspace, 1
bind = $mainMod SHIFT, W, movetoworkspace, 2
bind = $mainMod SHIFT, E, movetoworkspace, 3
bind = $mainMod SHIFT, R, movetoworkspace, 4

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
