monitor = eDP-1, 1920x1200, 1920x0, 1
monitor = DP-2, 1920x1080@60, 0x0, 1

workspace = 1, monitor:DP-2
workspace = 2, monitor:DP-2
workspace = 3, monitor:DP-2
workspace = 4, monitor:DP-2
workspace = 5, monitor:eDP-1

env = XCURSOR_SIZE,2
env = HYPRCURSOR_SIZE,2
env = XDG_CURRENT_DESKTOP,Hyprland

$terminalBash = kitty -e bash
$terminalZsh = kitty -e zsh
$fileManager = dolphin
$menu = tofi-run | xargs -r sh -c 
$mainMod = ALT
